DROP TABLE IF EXISTS `TEST`;
CREATE TABLE IF NOT EXISTS `SYS_LOG` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(20) DEFAULT NULL COMMENT '用户名',
  `OPERATION` VARCHAR(50) DEFAULT NULL COMMENT '用户操作',
  `TIME` BIGINT(20) DEFAULT NULL COMMENT '响应时间',
  `METHOD` VARCHAR(200) DEFAULT NULL COMMENT '请求方法',
  `PARAMS` VARCHAR(500) DEFAULT NULL COMMENT '请求参数',
  `IP` VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8
